### PR TITLE
Update for Xcode 7.3 support

### PR DESCRIPTION
**Pull request by grigaci**

### CODE REVIEW

**Comment by PaulTaykalo** [comment]
@grigaci Have you checked if its' working on Xcode 7.3?

**Comment by grigaci** [comment]
@PaulTaykalo I've manually updated the Info.plist into the installed plugin and it worked with Xcode 7.3.

**Comment by PaulTaykalo** [comment]
@grigaci Thanks

**Comment by grigaci** [comment]
@PaulTaykalo 😉

**Pull request merged**
